### ISSUE TITLE
Unhandled exception when shared postgres client disconnects occasionally

### ISSUE THREAD

**Issue by UoLeevi** [UoLeevi/duely#9]
## TODO:
 - [ ] make sure reconnecting is working

## Error dump
```
error on shared postgres client. Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:272:71)
    at Object.onceWrapper (events.js:421:28)
    at Connection.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:102:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by UoLeevi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [shared postgres client reconnection](https://trello.com/c/A6kViVNO/53-shared-postgres-client-reconnection)

**Comment by UoLeevi** [comment]
Subscriptions using websockets are currently not being used. This issue could be reopened if subscriptions are reimplemented and problem occurs again.
